/*
Copyright (c) 2023, Jörg 'MK2k' Sonntag, Steffen Stolze

Internet Consortium License (ISC)
*/
CREATE TABLE IF NOT EXISTS $schemaname.$tablename
(
  -- IMPORTANT: only provide a minimal set of columns in this CREATE statement, provide the rest in the ALTER statement below!
    id_$tablename BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  -- prefer integer PKs over UUIDs (faster and in sequence)
  , id_$anothertable BIGINT
  , PRIMARY KEY(id_col1, id_col2)                     -- use this if you need a composite PK
  , CONSTRAINT fk_$tablename_id_$anothertable         -- constraints must be provided in the CREATE statement, because we don't have "IF NOT EXISTS" for constraints
      FOREIGN KEY(id_$anothertable) 
	    REFERENCES $schemaname.$anothertable(id_$anothertable)
      ON DELETE { SET NULL | CASCADE | SET DEFAULT }  -- choose one
);

ALTER TABLE $schemaname.$tablename
    ADD COLUMN IF NOT EXISTS unrestricted_text TEXT [NOT] NULL                 -- there is no performance impact in using unrestricted TEXT columns
  , ADD COLUMN IF NOT EXISTS restricted_text VARCHAR(20) [NOT] NULL            -- only use restricted text columns if you are absolutely certain about the max. length; length is in characters and not bytes
  , ADD COLUMN IF NOT EXISTS whole_number BIGINT [NOT] NULL
  , ADD COLUMN IF NOT EXISTS exact_number NUMERIC [NOT] NULL                   -- allows for arbitrary precision, supports fractional numbers, great suited for monetary values, computations are slower but yield results without rounding errors
  , ADD COLUMN IF NOT EXISTS date_and_time TIMESTAMP WITH TIME ZONE [NOT] NULL -- actually DO STORE the timezone in timestamps etc.
  , ADD COLUMN IF NOT EXISTS flag BOOLEAN [NOT] NULL
  , ADD COLUMN IF NOT EXISTS json_formatted_data JSONB [NOT] NULL              -- JSONB (not JSON) allows for indexing, containment/existence and subscripting on the data 
  , ADD COLUMN IF NOT EXISTS localized_descriptions JSONB [NOT] NULL           -- localized descriptions/names etc., e.g.: {"de": "Der beste Becher", "en": "The best cup"}
  , %DEFAULT_COLUMNS%                                                          -- update-db provides default columns here (created_at, created_by, updated_at, updated_by, deleted_at, deleted_by, deleted_reason) - every table should have these columns
;

%DEFAULT_TRIGGER($schemaname.$tablename)%                                      -- creates update trigger which provide values to updated_at and updated_by

DROP INDEX IF EXISTS idx_$schemaname_$tablename_$columnnames;
CREATE [ UNIQUE ] INDEX IF NOT EXISTS idx_$schemaname_$tablename_$columnnames ON $schemaname.$tablename ( { $columnnames | ( expression ) } [ ASC | DESC ] [ NULLS { FIRST | LAST } ], ... );
